"""Multi-channel Alert System - SMS, Email, Push"""
import httpx
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Optional
import os
from datetime import datetime

# Configuration
TWILIO_SID = os.getenv("TWILIO_SID", "")
TWILIO_TOKEN = os.getenv("TWILIO_TOKEN", "")
TWILIO_PHONE = os.getenv("TWILIO_PHONE", "")
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")

# Alert recipients (to be configured in admin panel)
ALERT_CONTACTS = {
    "commissioner": {"phone": "+234XXXXXXXXX", "email": "commissioner@kebbi.gov.ng"},
    "operations": {"phone": "+234XXXXXXXXX", "email": "ops@kebbi.gov.ng"},
    "intel": {"phone": "+234XXXXXXXXX", "email": "intel@kebbi.gov.ng"},
}


class AlertManager:
    """Centralized alert management"""
    
    CRITICAL_KEYWORDS = {"bandit", "attack", "kidnapping", "kill", "ambush", "massacre"}
    
    @staticmethod
    def classify_alert_severity(text: str) -> str:
        """Classify alert severity based on content"""
        text_lower = text.lower()
        if any(kw in text_lower for kw in AlertManager.CRITICAL_KEYWORDS):
            return "CRITICAL"
        elif "security" in text_lower or "threat" in text_lower:
            return "HIGH"
        return "MEDIUM"
    
    @staticmethod
    async def send_sms(phone: str, message: str) -> bool:
        """Send SMS via Twilio or Termii (Nigeria)"""
        try:
            # Try Termii first (better for Nigeria)
            termii_key = os.getenv("TERMII_KEY", "")
            if termii_key:
                url = "https://api.ng.termii.com/api/sms/send"
                payload = {
                    "to": phone,
                    "from": "CITADEL",
                    "sms": message[:160],  # SMS limit
                    "type": "plain",
                    "channel": "generic",
                    "api_key": termii_key,
                }
                async with httpx.AsyncClient() as client:
                    resp = await client.post(url, json=payload)
                    return resp.status_code == 200
            
            # Fallback to Twilio
            if TWILIO_SID and TWILIO_TOKEN:
                url = f"https://api.twilio.com/2010-04-01/Accounts/{TWILIO_SID}/Messages.json"
                async with httpx.AsyncClient() as client:
                    resp = await client.post(
                        url,
                        auth=(TWILIO_SID, TWILIO_TOKEN),
                        data={"From": TWILIO_PHONE, "To": phone, "Body": message[:160]}
                    )
                    return resp.status_code == 201
            
            return False
        except Exception as e:
            print(f"[SMS Alert Error] {e}")
            return False
    
    @staticmethod
    async def send_email(recipients: List[str], subject: str, body: str, is_html: bool = False) -> bool:
        """Send email alerts"""
        try:
            if not SMTP_USER or not SMTP_PASS:
                return False
            
            msg = MIMEMultipart()
            msg['From'] = SMTP_USER
            msg['To'] = ", ".join(recipients)
            msg['Subject'] = f"[CITADEL KEBBI] {subject}"
            
            content_type = 'html' if is_html else 'plain'
            msg.attach(MIMEText(body, content_type))
            
            with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USER, SMTP_PASS)
                server.send_message(msg)
            
            return True
        except Exception as e:
            print(f"[Email Alert Error] {e}")
            return False
    
    @staticmethod
    async def send_security_alert(title: str, description: str, location: str = ""):
        """Send security alert via all channels"""
        severity = AlertManager.classify_alert_severity(title + " " + description)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M WAT")
        
        # SMS Message (short)
        sms_msg = f"{severity} ALERT: {title[:80]}. Location: {location[:30]}. Time: {timestamp}. CITADEL KEBBI"
        
        # Email Message (detailed)
        email_body = f"""
        <h2 style='color: {"#ff0000" if severity == "CRITICAL" else "#ff6600"};'>
            {severity} SECURITY ALERT
        </h2>
        <p><strong>Title:</strong> {title}</p>
        <p><strong>Description:</strong> {description}</p>
        <p><strong>Location:</strong> {location}</p>
        <p><strong>Time:</strong> {timestamp}</p>
        <hr>
        <p><em>Alert generated by CITADEL KEBBI Intelligence System</em></p>
        <p>View full details: https://security-ai-fushion-dashboard-kb.netlify.app</p>
        """
        
        # Send to all configured contacts
        results = {"sms": [], "email": []}
        
        for role, contact in ALERT_CONTACTS.items():
            # Send SMS for critical alerts
            if severity == "CRITICAL" and contact.get("phone"):
                success = await AlertManager.send_sms(contact["phone"], sms_msg)
                results["sms"].append({"role": role, "success": success})
            
            # Send email
            if contact.get("email"):
                success = await AlertManager.send_email(
                    [contact["email"]],
                    f"{severity}: {title[:50]}",
                    email_body,
                    is_html=True
                )
                results["email"].append({"role": role, "success": success})
        
        return results
    
    @staticmethod
    async def send_fire_alert(lat: float, lon: float, brightness: float, acq_date: str):
        """Specialized fire detection alert"""
        location = f"{lat:.4f}°N, {lon:.4f}°E"
        severity = "CRITICAL" if brightness > 350 else "HIGH"
        
        title = f"Fire Hotspot Detected - {severity}"
        description = f"NASA FIRMS detected thermal anomaly. Brightness: {brightness}K. Potential security threat or arson activity."
        
        return await AlertManager.send_security_alert(title, description, location)
    
    @staticmethod
    async def send_satellite_overhead_alert(satellite: str, minutes_until: int):
        """Alert when satellite is passing overhead"""
        if minutes_until == 5:  # 5-minute warning
            title = f"{satellite} Overhead in 5 Minutes"
            description = f"Satellite imaging window approaching. Ensure sensitive activities are masked."
            
            sms = f"SATELLITE ALERT: {satellite} overhead in 5 mins. Time: {datetime.now().strftime('%H:%M')}"
            
            for role, contact in ALERT_CONTACTS.items():
                if contact.get("phone"):
                    await AlertManager.send_sms(contact["phone"], sms)


# Global alert manager
alert_manager = AlertManager()
